stages:
- name: "1"
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: library/demo
      pushRemote: true
      registry: index.docker.io
timeout: 60
