stages:
- name: 构建1
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: ls
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 111/111:123
      pushRemote: true
      registry: 1.1.1.1
  when:
    branch:
      include:
      - test
    event:
      include:
      - tag
- name: 构建2
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: ls
  when:
    branch:
      include:
      - demo
    event:
      include:
      - tag
timeout: 60
notification: {}
