stages:
- name: 111111111111111111111111ddddddddddddddddddd11
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hongxiaolu/test:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.docker.io
    env:
      PLUGIN_STORAGE_PATH: /var/lib/docker2
      PLUGIN_TAG: test
  - runScriptConfig:
      image: docker:dind
      shellScript: ls
  when:
    branch:
      include:
      - test
    event:
      include:
      - tag
timeout: 60
notification: {}
