stages:
- name: 111111111111111111111111ddddddddddddddddddd11
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hongxiaolu/test:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.docker.io
  - runScriptConfig:
      image: php:latest
      shellScript: ls
timeout: 60
