stages:
- name: "11111111111111111111111111"
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: library/demo
      pushRemote: true
      registry: index.docker.io
timeout: 60
