stages:
- name: "1"
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: library/demo
      pushRemote: true
      registry: 192.168.1.13:8443
timeout: 60
