{{- $network := $.Values.fabricNetwork -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ $network }}-explorer-mysql
spec:
  selector:
    app: {{ $network }}-explorer-mysql
  ports:
    - protocol: TCP
      port: 3306
