{{ if .Values.explorer.enabled }}
{{- $network := $.Values.fabricNetwork -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ $network }}-explorer
spec:
  type: LoadBalancer
  selector:
    app: {{ $network }}-explorer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      
---

{{ end }}
