{{- $brokerNum := 4 -}}
{{- $portList := list 9092 9093 9094 9095 -}}
{{- $network := $.Values.fabricNetwork -}}
{{- range $loopIndex, $brokerIndex := untilStep 1 (int (add $brokerNum 1)) 1 -}}
kind: Service
apiVersion: v1
metadata:
  name: network01-kafka{{ $brokerIndex }}
spec:
  # Use headless service to tolerate k8s env which disables hairpin mode
  clusterIP: None
  selector:
    app: network01-kafka{{ $brokerIndex }}
  ports:
    - protocol: TCP
      port: {{ index $portList $loopIndex }}
      name: kafka-port

---

{{- end -}}
