{{- $ordererNum := int $.Values.ordererNum }}
{{- $network := $.Values.fabricNetwork -}}
{{- range $loopIndex, $ordererIndex := untilStep 1 (int (add $ordererNum 1)) 1 -}}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ $network }}-orderer{{ $ordererIndex }}
spec:
  type: NodePort
  selector:
    app: {{ $network }}-orderer{{ $ordererIndex }}
  ports:
    - protocol: TCP
      port: 7050
      nodePort: {{ index $.Values.ordererExternalPortList $loopIndex }}
      name: orderer-port

{{- end -}}
