{{- $orgNum := int $.Values.orgNum }}
{{- $peerNum := int (mul $orgNum 2) }}
{{- $network := $.Values.fabricNetwork -}}
{{- $orgMspList := splitList " " ((include "orgMspList" .) | trimSuffix " ") -}}
{{- range $loopIndex, $peerIndex := untilStep 1 (int (add $peerNum 1)) 1 -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ $network }}-peer{{ $peerIndex }}
spec:
  type: NodePort
  selector:
    app: {{ $network }}-peer{{ $peerIndex }}
  ports:
    - protocol: TCP
      port: 7051
      nodePort: {{ index $.Values.peerExternalGrpcPortList $loopIndex }}
      name: grpc-port
    - protocol: TCP
      port: 7053
      nodePort: {{ index $.Values.peerExternalEventPortList $loopIndex }}
      name: event-port
      
---

{{- end -}}
