{{- $zkNum := 3 -}}
{{- range $loopIndex, $zkIndex := untilStep 1 (int (add $zkNum 1)) 1 -}}
kind: Service
apiVersion: v1
metadata:
  name: network01-zookeeper{{ $zkIndex }}
spec:
  selector:
    app: network01-zookeeper{{ $zkIndex }}
  ports:
    - protocol: TCP
      port: 2181
      name: client-port
    - protocol: TCP
      port: 2888
      name: follower-port
    - protocol: TCP
      port: 3888
      name: election-port
      
---

{{- end -}}
